[Runtime]
verbosity=10
[Debug]
aie_trace = true
ml_timeline = true
# This flag is needed to enable trace on XDNA side for Telluride. By default, zocl mode is enabled.
xdp_mode = xdna
[AIE_trace_settings]
buffer_size=128M
tile_based_aie_tile_metrics = all:all_stalls
tile_based_memory_tile_metrics = all:input_channels_stalls
tile_based_interface_tile_metrics = all:input_output_ports
